### ISSUE TITLE
Grammer in privacy warning

### ISSUE THREAD

**Issue by nsearls-bu** [hicsail/fhs-online-inquiry-system-backend#13]
"There are 1 participants that fit the criteriea. For the sake of privacy, we will not show the specifics. Please contact us for more info"

Should be "there is 1 participant"

**Comment by wenhwang97** [comment]
Also, should we put the threshold on each type rather than then entire result? In case the result contains only 1 male and 5 females, it will still pass the current threshold. However, we are still showing the individual data. If we want to do this, probably we can put the threshold lower since we only have a small dummy dataset now.
